# Generated by Django 6.0.1 on 2026-03-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_and_fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date',
        ),
    ]
