# Generated by Django 6.0.1 on 2026-03-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_and_fitness_app', '0002_remove_userprofile_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodystats',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='user_id',
            new_name='user',
        ),
    ]
